Traceback (most recent call last):
  File "c:\Shaurya\Longformer2\LongformerCoLA\src\trainmodel.py", line 44, in <module>
    main(arguments)
  File "c:\Shaurya\Longformer2\LongformerCoLA\src\trainmodel.py", line 25, in main
    train_model(config)
  File "c:\Shaurya\Longformer2\LongformerCoLA\src\utils\train.py", line 112, in train_model
    config.to(device)
AttributeError: 'dict' object has no attribute 'to'