2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Configure stats pid to 24272
2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Shaurya\.config\wandb\settings
2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Loading settings from C:\Shaurya\Longformer2\wandb\settings
2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-25 19:05:00,802 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'LongformerCoLA\\src\\trainmodel.py', 'program_abspath': 'c:\\Shaurya\\Longformer2\\LongformerCoLA\\src\\trainmodel.py', 'program': 'c:\\Shaurya\\Longformer2\\LongformerCoLA\\src\\trainmodel.py'}
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:_log_setup():526] Logging user logs to C:\Shaurya\Longformer2\wandb\run-20240325_190500-hgyh88ae\logs\debug.log
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Shaurya\Longformer2\wandb\run-20240325_190500-hgyh88ae\logs\debug-internal.log
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:init():566] calling init triggers
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'architecture': 'BERT(Restructured)', 'dataset': 'CoLA', 'epochs': 6}
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:init():616] starting backend
2024-03-25 19:05:00,810 INFO    MainThread:24272 [wandb_init.py:init():620] setting up manager
2024-03-25 19:05:00,811 INFO    MainThread:24272 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-25 19:05:00,815 INFO    MainThread:24272 [wandb_init.py:init():628] backend started and connected
2024-03-25 19:05:00,818 INFO    MainThread:24272 [wandb_init.py:init():720] updated telemetry
2024-03-25 19:05:00,864 INFO    MainThread:24272 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-25 19:06:31,677 ERROR   MainThread:24272 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-25 19:06:32,091 ERROR   MainThread:24272 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\Shaurya\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "C:\Users\Shaurya\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-25 19:06:33,107 WARNING MsgRouterThr:24272 [router.py:message_loop():77] message_loop has been closed
